import { createClient } from "npm:@supabase/supabase-js@2.110.9";
import { createRemoteJWKSet, decodeProtectedHeader, importX509, jwtVerify, type JWTPayload } from "npm:jose@6.2.3";

const FIREBASE_PROJECT_ID="dimosrodou-otp";
const FIREBASE_PROJECT_NUMBER="315292350668";
const FIREBASE_WEB_APP_ID="1:315292350668:web:8288883847d24ac33e2a69";
const FIREBASE_ISSUER=`https://securetoken.google.com/${FIREBASE_PROJECT_ID}`;
const FIREBASE_CERTS_URL="https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com";
const APP_CHECK_ISSUER=`https://firebaseappcheck.googleapis.com/${FIREBASE_PROJECT_NUMBER}`;
const APP_CHECK_AUDIENCE=`projects/${FIREBASE_PROJECT_NUMBER}`;
const APP_CHECK_JWKS=createRemoteJWKSet(new URL("https://firebaseappcheck.googleapis.com/v1/jwks"));
const MODIFY_WINDOW_MIN=10, MAX_JSON_BYTES=512*1024, DEFAULT_ORIGIN="https://vasilis1730-web.github.io";
const LIST_PAGE_SIZE=500, MAX_LIST_SCAN_ROWS=10000;
const CITIZEN_MUNICIPALITIES=new Set([
  "Δημοτική Κοινότητα Ρόδου","Δημοτική Κοινότητα Αρχαγγέλου","Δημοτική Κοινότητα Μαλώνος","Τοπική Κοινότητα Μασάρων","Δημοτική Κοινότητα Έμπωνα","Τοπική Κοινότητα Αγίου Ισιδώρου","Τοπική Κοινότητα Κρητηνίας","Τοπική Κοινότητα Μονολίθου","Τοπική Κοινότητα Σιάνων","Δημοτική Κοινότητα Αφάντου","Τοπική Κοινότητα Αρχιπόλεως","Δημοτική Κοινότητα Ιαλυσού","Δημοτική Κοινότητα Καλυθιών","Δημοτική Κοινότητα Κοσκινού","Δημοτική Κοινότητα Ψίνθου","Δημοτική Κοινότητα Σορωνής","Τοπική Κοινότητα Απόλλωνα","Τοπική Κοινότητα Διμυλιάς","Τοπική Κοινότητα Καλαβάρδα","Τοπική Κοινότητα Πλατανίων","Τοπική Κοινότητα Σαλάκου","Τοπική Κοινότητα Φανών","Δημοτική Κοινότητα Λάρδου","Δημοτική Κοινότητα Λίνδου","Τοπική Κοινότητα Καλάθου","Τοπική Κοινότητα Λαέρμων","Τοπική Κοινότητα Πυλώνος","Τοπική Κοινότητα Απολακκιάς","Τοπική Κοινότητα Αρνίθας","Τοπική Κοινότητα Ασκληπιείου","Τοπική Κοινότητα Βατίου","Τοπική Κοινότητα Γενναδίου","Τοπική Κοινότητα Ιστρίου","Τοπική Κοινότητα Κατταβίας","Τοπική Κοινότητα Λαχανιάς","Τοπική Κοινότητα Μεσαναγρού","Τοπική Κοινότητα Προφίλιας","Δημοτική Κοινότητα Κρεμαστής","Δημοτική Κοινότητα Μαριτσών","Δημοτική Κοινότητα Παραδεισίου","Δημοτική Κοινότητα Παστίδας","Τοπική Κοινότητα Δαματρίας",
]);
const CITIZEN_TITLES:Record<string,ReadonlySet<string>>={
  "Οδοστρωσία":new Set(["Λακκούβες / φθορές οδοστρώματος","Υποχώρηση ή κατάρρευση οδοστρώματος","Ρωγμές / σχισμές ασφάλτου","Ανοιχτό / επικίνδυνο φρεάτιο","Ζημιά από έργα τρίτων (ΔΕΥΑΡ κ.λπ.)","Άλλο"]),
  "Πεζοδρόμια/Πλατείες":new Set(["Σπασμένες / ανυψωμένες πλάκες πεζοδρομίου","Επικίνδυνο / αναπηρικό ανεπαρκές πεζοδρόμιο","Φθορές σε πλατεία / χώρο αναψυχής","Έλλειψη ράμπας πρόσβασης ΑΜΕΑ","Παράνομες διαγραμμίσεις / ράμπες","Άλλο"]),
  "Ηλεκτροφωτισμός":new Set(["Καμένη λάμπα / φωτιστικό εκτός","Σβηστό δίκτυο φωτισμού (πολλές κολώνες)","Κλίνουσα / επικίνδυνη κολώνα φωτισμού","Βλάβη ηλεκτρολογικού πίνακα / καφάο","Φωτισμός ανάβει λάθος ώρες","Άλλο"]),
  "Υδραυλικά":new Set(["Διαρροή / σπασμένη σωλήνωση","Βλάβη βάνας / δικλείδας","Απόφραξη αποχέτευσης / φρεατίου","Βλάβη υδραυλικής εγκατάστασης κτιρίου","Έλλειψη νερού σε εγκατάσταση","Άλλο"]),
  "Κτιριακές Εγκαταστάσεις":new Set(["Βλάβη κλειδαριάς / πόρτας / παραθύρου","Υγρασία / διαρροή οροφής / στέγης","Φθορά / ζημιά εσωτερικού χώρου","Ετοιμόρροπο κτίριο / στέγη","Βλάβη ηλεκτρολογικής εγκατάστασης κτιρίου","Άλλο"]),
  "Σχολικά Κτίρια":new Set(["Βλάβη υδραυλικής (τουαλέτες / νιπτήρες)","Βλάβη ηλεκτρολογικής εγκατάστασης","Ξυλουργικές εργασίες (πόρτες / παράθυρα)","Φθορές αύλειου χώρου / περίφραξης","Διαρροή / υγρασία οροφής","Άλλο"]),
  "Παιδικές Χαρές":new Set(["Σπασμένο / επικίνδυνο όργανο παιδικής χαράς","Φθορά ελαστικού δαπέδου ασφαλείας","Βλάβη / έλλειψη περίφραξης","Συσσώρευση σκουπιδιών / ακαθαρσιών","Έλλειψη πιστοποίησης ασφαλείας οργάνου","Άλλο"]),
  "Αστικός Εξοπλισμός":new Set(["Πεσμένη / κατεστραμμένη πινακίδα σήμανσης","Βλάβη / έλλειψη κάδου απορριμμάτων","Φθορά παγκακίου / αστικού εξοπλισμού","Έλλειψη / βλάβη διαγράμμισης οδού","Βλάβη φαναριού / σηματοδότη","Άλλο"]),
  "Λοιπές Εργασίες":new Set(["Αποκομιδή μπαζών / αδρανών υλικών","Εργασίες καθαρισμού χώρου","Ράμπα πρόσβασης ΑΜΕΑ","Γενική βλάβη / επείγουσα επέμβαση","Παροχή εργατικού δυναμικού","Άλλο"]),
};
type FirebasePayload=JWTPayload&{phone_number?:string;firebase?:{sign_in_provider?:string};auth_time?:number};
class HttpError extends Error{status:number;publicMessage:string;constructor(status:number,publicMessage:string,internalMessage?:string){super(internalMessage||publicMessage);this.status=status;this.publicMessage=publicMessage;}}
function allowedOrigins(){const extra=(Deno.env.get("RODIOS_ALLOWED_ORIGINS")||"").split(",").map(x=>x.trim()).filter(Boolean);return new Set([DEFAULT_ORIGIN,...extra]);}
function corsHeaders(req:Request){const origin=req.headers.get("origin")||"";const h:Record<string,string>={"Access-Control-Allow-Headers":"content-type, apikey, x-firebase-id-token, x-firebase-appcheck","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"};if(origin&&allowedOrigins().has(origin))h["Access-Control-Allow-Origin"]=origin;return h;}
function assertOrigin(req:Request){const origin=req.headers.get("origin")||"";if(origin&&!allowedOrigins().has(origin))throw new HttpError(403,"Origin not allowed");}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
function getAdminClient(){const url=(Deno.env.get("SUPABASE_URL")||"").trim();let key=(Deno.env.get("SUPABASE_SECRET_KEY")||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"").trim();if(!key){try{const named=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");key=String(named.default||Object.values(named)[0]||"").trim();}catch(_){}}if(!url||!key)throw new Error("Supabase server credentials are not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
let certCache:{keys:Record<string,string>;exp:number}|null=null;
function parseMaxAge(v:string|null){const m=String(v||"").match(/(?:^|,)\s*max-age=(\d+)/i);return m?Math.max(60,Number(m[1])||300):300;}
async function getFirebaseCerts(){const now=Date.now();if(certCache&&certCache.exp>now)return certCache.keys;const res=await fetch(FIREBASE_CERTS_URL,{headers:{Accept:"application/json"}});if(!res.ok)throw new Error(`Firebase certificate endpoint returned ${res.status}`);const keys=await res.json();if(!keys||typeof keys!=="object")throw new Error("Firebase certificate response is invalid");certCache={keys:keys as Record<string,string>,exp:now+parseMaxAge(res.headers.get("cache-control"))*1000};return certCache.keys;}
async function verifyFirebaseIdToken(token:string):Promise<FirebasePayload>{if(!token||token.length>20000)throw new Error("Missing or malformed Firebase ID token");const header=decodeProtectedHeader(token);if(header.alg!=="RS256"||!header.kid)throw new Error("Invalid Firebase token header");const certs=await getFirebaseCerts(),pem=certs[String(header.kid)];if(!pem)throw new Error("Unknown Firebase signing key");const key=await importX509(pem,"RS256");const {payload}=await jwtVerify(token,key,{algorithms:["RS256"],issuer:FIREBASE_ISSUER,audience:FIREBASE_PROJECT_ID});const p=payload as FirebasePayload,now=Math.floor(Date.now()/1000);if(!p.sub||typeof p.sub!=="string"||p.sub.length>128)throw new Error("Invalid Firebase subject");if(!p.iat||p.iat>now+60)throw new Error("Invalid Firebase issued-at");if(!p.auth_time||p.auth_time>now+60)throw new Error("Invalid Firebase auth_time");if(p.firebase?.sign_in_provider!=="phone")throw new Error("Firebase phone authentication required");if(!p.phone_number)throw new Error("Verified phone number missing");return p;}
async function verifyAppCheckToken(token:string){if(!token||token.length>20000)throw new Error("Missing or malformed Firebase App Check token");const header=decodeProtectedHeader(token);if(header.alg!=="RS256"||header.typ!=="JWT"||!header.kid)throw new Error("Invalid App Check header");const {payload}=await jwtVerify(token,APP_CHECK_JWKS,{algorithms:["RS256"],issuer:APP_CHECK_ISSUER,audience:APP_CHECK_AUDIENCE});if(payload.sub!==FIREBASE_WEB_APP_ID)throw new Error("App Check app id is not authorized");}
function digits(p:string){return String(p||"").replace(/\D/g,"");}
function localPhoneKey(p:string){const d=digits(p);return d.startsWith("30")&&d.length===12?d.slice(2):d;}
function belongsPhone(issue:any,phone:string){const expected=localPhoneKey(phone);if(!expected)return false;return [issue?.citizenMobile,issue?.citizenPhone,issue?.mobile].map(localPhoneKey).filter(Boolean).includes(expected);}
function cleanText(v:unknown,max:number){return String(v??"").trim().slice(0,max);}
function cleanNullableNumber(v:unknown,min:number,max:number){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null;}
function newCitizenRef(){return crypto.randomUUID().replaceAll("-","").slice(0,12).toUpperCase();}
function cleanAttachments(v:unknown,phoneDigits:string){if(!Array.isArray(v))return [];const prefix=`citizen/${phoneDigits}/`;return v.slice(0,20).flatMap((x:any)=>{const path=cleanText(x?.path,600).replace(/^\/+/,"");if(!path||!path.startsWith(prefix)||path.includes(".."))return [];return [{name:cleanText(x?.name,160)||"attachment",type:cleanText(x?.type,120),size:Math.max(0,Math.min(Number(x?.size)||0,50*1024*1024)),path,url:null}];});}
function cleanLegacyAttachmentUrl(v:unknown){try{const project=new URL((Deno.env.get("SUPABASE_URL")||"").trim()),u=new URL(cleanText(v,2000));let path="";try{path=decodeURIComponent(u.pathname);}catch(_){return "";}if(u.protocol!=="https:"||u.host!==project.host)return "";return /^\/storage\/v1\/object\/(?:sign|authenticated|public)\/attachments\//.test(path)?u.href:"";}catch(_){return "";}}
function legacyPathlessAttachments(v:unknown){if(!Array.isArray(v))return [];return v.slice(0,20).flatMap((x:any)=>{if(cleanText(x?.path,600))return [];const url=cleanLegacyAttachmentUrl(x?.url);if(!url)return [];return [{name:cleanText(x?.name,160)||"attachment",type:cleanText(x?.type,120),size:Math.max(0,Math.min(Number(x?.size)||0,50*1024*1024)),path:"",url}];});}
function mergeUpdatedAttachments(original:unknown,incoming:unknown,phoneDigits:string){return [...legacyPathlessAttachments(original),...cleanAttachments(incoming,phoneDigits)].slice(0,20);}
function assertCitizenClassification(municipality:string,category:string,title:string){if(!CITIZEN_MUNICIPALITIES.has(municipality)||!CITIZEN_TITLES[category]?.has(title))throw new HttpError(400,"Μη έγκυρη κοινότητα, κατηγορία ή τίτλος αιτήματος.");}
function publicIssue(issue:any){const x=issue&&typeof issue==="object"?issue:{};return {id:cleanText(x.id,180),citizenRef:cleanText(x.citizenRef,30),issueNum:cleanText(x.issueNum,80),modifiesRef:cleanText(x.modifiesRef,60)||null,createdAt:cleanText(x.createdAt,80),lastModifiedAt:cleanText(x.lastModifiedAt,80),source:x.source==="citizen"?"citizen":"",date:cleanText(x.date,20),time:cleanText(x.time,20),citizenName:cleanText(x.citizenName,180),municipality:cleanText(x.municipality,160),category:cleanText(x.category,160),title:cleanText(x.title,220),location:cleanText(x.location,300),description:cleanText(x.description,5000),status:cleanText(x.status,160),municipalNum:cleanText(x.municipalNum,100),mapLat:cleanNullableNumber(x.mapLat,-90,90),mapLng:cleanNullableNumber(x.mapLng,-180,180),attachments:(Array.isArray(x.attachments)?x.attachments:[]).slice(0,20).map((a:any)=>({name:cleanText(a?.name,160)||"attachment",type:cleanText(a?.type,120),size:Math.max(0,Math.min(Number(a?.size)||0,50*1024*1024)),path:cleanText(a?.path,600),url:null})),completionDate:cleanText(x.completionDate,30)};}
function athensParts(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return{date:`${get("year")}-${get("month")}-${get("day")}`,time:`${get("hour")}:${get("minute")}`};}
async function consumeQuota(admin:any,scope:string,actor:string,limit:number){const {data,error}=await admin.rpc("rodios_consume_edge_quota",{p_scope:scope,p_actor_key:actor,p_limit:limit});if(error)throw new Error(`Rate-limit RPC failed: ${error.message}`);if(data!==true)throw new HttpError(429,"Πάρα πολλές αιτήσεις. Δοκιμάστε ξανά αργότερα.");}
async function fetchCitizenRows(admin:any,uid:string|null){const rows:any[]=[];for(let from=0;;from+=LIST_PAGE_SIZE){const requested=Math.min(LIST_PAGE_SIZE,MAX_LIST_SCAN_ROWS+1-from);if(requested<=0)throw new HttpError(503,"Υπάρχουν υπερβολικά πολλά αιτήματα για ασφαλή φόρτωση.");let query=admin.from("rodios_issues").select("id, data, updated_at").is("deleted_at",null).eq("data->>source","citizen").order("updated_at",{ascending:false}).order("id",{ascending:true});if(uid)query=query.eq("data->>citizenAuthUid",uid);const {data,error}=await query.range(from,from+requested-1);if(error)throw error;const page=data||[];rows.push(...page);if(rows.length>MAX_LIST_SCAN_ROWS)throw new HttpError(503,"Υπάρχουν υπερβολικά πολλά αιτήματα για ασφαλή φόρτωση.");if(page.length<requested)return rows;}}
async function listCitizenIssues(admin:any,uid:string,phone:string){const [uidRows,legacyRows]=await Promise.all([fetchCitizenRows(admin,uid),fetchCitizenRows(admin,null)]);const byId=new Map<string,any>();for(const row of uidRows)byId.set(row.id,{...row.data,id:row.id,_dbUpdatedAt:row.updated_at});for(const row of legacyRows){if(byId.has(row.id)||row?.data?.citizenAuthUid)continue;if(belongsPhone(row.data,phone))byId.set(row.id,{...row.data,id:row.id,_dbUpdatedAt:row.updated_at});}return [...byId.values()].sort((a,b)=>String(b._dbUpdatedAt||b.lastModifiedAt||b.createdAt||"").localeCompare(String(a._dbUpdatedAt||a.lastModifiedAt||a.createdAt||""))).map(publicIssue);}
async function getIssue(admin:any,id:string){const {data,error}=await admin.from("rodios_issues").select("id, data").eq("id",id).is("deleted_at",null).maybeSingle();if(error)throw error;return data?{...data.data,id:data.id}:null;}
async function ownsCitizenRef(admin:any,ref:string,uid:string,phone:string){if(!ref)return true;const {data,error}=await admin.from("rodios_issues").select("data").is("deleted_at",null).eq("data->>source","citizen").eq("data->>citizenRef",ref).limit(20);if(error)throw error;return (data||[]).some((row:any)=>String(row?.data?.citizenAuthUid||"")===uid||(!row?.data?.citizenAuthUid&&belongsPhone(row?.data,phone)));}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS"){try{assertOrigin(req);return new Response(null,{status:204,headers:corsHeaders(req)});}catch(_){return json(req,{ok:false,error:"Origin not allowed"},403);}}if(req.method!=="POST")return json(req,{ok:false,error:"Method not allowed"},405);
try{assertOrigin(req);const length=Number(req.headers.get("content-length")||"0");if(length>MAX_JSON_BYTES)throw new HttpError(413,"Το αίτημα είναι πολύ μεγάλο.");let body:any;try{body=await req.json();}catch{throw new HttpError(400,"Invalid JSON");}
const idToken=req.headers.get("x-firebase-id-token")||"",appCheckToken=req.headers.get("x-firebase-appcheck")||"";const [claims]=await Promise.all([verifyFirebaseIdToken(idToken),verifyAppCheckToken(appCheckToken)]);const phone=String(claims.phone_number||""),phoneDigits=digits(phone);if(!/^3069\d{8}$/.test(phoneDigits))throw new HttpError(401,"Invalid verified Greek mobile phone");const admin=getAdminClient();const action=cleanText(body?.action,20),limits:Record<string,number>={list:120,submit:20,update:60};if(!(action in limits))throw new HttpError(400,"Unknown action");await consumeQuota(admin,`citizen-bridge:${action}`,String(claims.sub),limits[action]);
if(action==="list")return json(req,{ok:true,issues:await listCitizenIssues(admin,String(claims.sub),phone)});
if(action==="submit"){
  const inc=body?.issue&&typeof body.issue==="object"?body.issue:{};
  const citizenName=cleanText(inc.citizenName,180),municipality=cleanText(inc.municipality,160),category=cleanText(inc.category,160),title=cleanText(inc.title,220),location=cleanText(inc.location,300),description=cleanText(inc.description,5000),modifiesRef=cleanText(inc.modifiesRef,60)||null;
  if(!citizenName||!municipality||!category||!title||!location||!description)throw new HttpError(400,"Λείπουν υποχρεωτικά πεδία.");
  assertCitizenClassification(municipality,category,title);
  if(modifiesRef&&!await ownsCitizenRef(admin,modifiesRef,String(claims.sub),phone))throw new HttpError(403,"Invalid modification reference");
  const nowIso=new Date().toISOString(),local=athensParts();
  const issue={id:`cit_${crypto.randomUUID()}`,citizenRef:newCitizenRef(),issueNum:"",modifiesRef,createdAt:nowIso,serverReceivedAt:nowIso,source:"citizen",date:local.date,time:local.time,receiptMethod:"Αίτημα Πολίτη",citizenAuthUid:String(claims.sub),citizenName,citizenAddr:"",citizenMobile:phone,citizenPhone:phone,citizenEmail:"",contactInfo:`📱 ${phone}`,location,municipality,category,title,description,priority:"",danger:"Όχι",inspection:"Όχι",status:"Προς ενέργεια",notes:"",municipalNum:"",mapLat:cleanNullableNumber(inc.mapLat,-90,90),mapLng:cleanNullableNumber(inc.mapLng,-180,180),attachments:cleanAttachments(inc.attachments,phoneDigits),completionDate:""};
  const {error}=await admin.from("rodios_issues").insert({id:issue.id,data:issue,deleted_at:null});
  if(error)throw error;
  return json(req,{ok:true,issue:publicIssue(issue)});
}
const inc=body?.issue&&typeof body.issue==="object"?body.issue:{},id=cleanText(inc.id,180);
if(!id)throw new HttpError(400,"Missing id");
const orig=await getIssue(admin,id);
if(!orig)throw new HttpError(404,"Not found");
const uidOwned=orig.citizenAuthUid&&String(orig.citizenAuthUid)===String(claims.sub),legacyOwned=!orig.citizenAuthUid&&belongsPhone(orig,phone);
if(!uidOwned&&!legacyOwned)throw new HttpError(403,"Forbidden");
const createdMs=Date.parse(String(orig.createdAt||""));
if(!Number.isFinite(createdMs))throw new HttpError(409,"Modify window expired");
const ageMin=(Date.now()-createdMs)/60000;
if(ageMin< -2||ageMin>MODIFY_WINDOW_MIN)throw new HttpError(409,"Modify window expired");
const citizenName=cleanText(inc.citizenName??orig.citizenName,180),municipality=cleanText(inc.municipality??orig.municipality,160),category=cleanText(inc.category??orig.category,160),title=cleanText(inc.title??orig.title,220),location=cleanText(inc.location??orig.location,300),description=cleanText(inc.description??orig.description,5000);
if(!citizenName||!municipality||!category||!title||!location||!description)throw new HttpError(400,"Λείπουν υποχρεωτικά πεδία.");
assertCitizenClassification(municipality,category,title);
const updated={...orig,citizenAuthUid:String(claims.sub),citizenName,municipality,category,title,location,description,mapLat:cleanNullableNumber(inc.mapLat??orig.mapLat,-90,90),mapLng:cleanNullableNumber(inc.mapLng??orig.mapLng,-180,180),attachments:mergeUpdatedAttachments(orig.attachments,Array.isArray(inc.attachments)?inc.attachments:orig.attachments,phoneDigits),citizenMobile:phone,citizenPhone:phone,contactInfo:`📱 ${phone}`,lastModifiedAt:new Date().toISOString()};
const {error}=await admin.from("rodios_issues").update({data:updated}).eq("id",id).is("deleted_at",null);
if(error)throw error;
return json(req,{ok:true,issue:publicIssue(updated)});
}catch(err){const e=err instanceof Error?err:new Error(String(err));if(e instanceof HttpError){console.warn(`[citizen-bridge] ${e.status}: ${e.message}`);return json(req,{ok:false,error:e.publicMessage},e.status);}console.error("[citizen-bridge]",e);const authFailure=/Firebase|App Check|phone|token|subject|issued-at|auth_time/i.test(e.message);return json(req,{ok:false,error:authFailure?"Authentication failed":"Server request failed"},authFailure?401:500);}});
