import { createClient } from "npm:@supabase/supabase-js@2.110.9";
import { createRemoteJWKSet, decodeProtectedHeader, importX509, jwtVerify, type JWTPayload } from "npm:jose@6.2.3";

const FIREBASE_PROJECT_ID="dimosrodou-otp";
const FIREBASE_PROJECT_NUMBER="315292350668";
const FIREBASE_WEB_APP_ID="1:315292350668:web:8288883847d24ac33e2a69";
const FIREBASE_ISSUER=`https://securetoken.google.com/${FIREBASE_PROJECT_ID}`;
const FIREBASE_CERTS_URL="https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com";
const APP_CHECK_ISSUER=`https://firebaseappcheck.googleapis.com/${FIREBASE_PROJECT_NUMBER}`;
const APP_CHECK_AUDIENCE=`projects/${FIREBASE_PROJECT_NUMBER}`;
const APP_CHECK_JWKS=createRemoteJWKSet(new URL("https://firebaseappcheck.googleapis.com/v1/jwks"));
const MODIFY_WINDOW_MIN=10, MAX_JSON_BYTES=512*1024, DEFAULT_ORIGIN="https://vasilis1730-web.github.io";
type FirebasePayload=JWTPayload&{phone_number?:string;firebase?:{sign_in_provider?:string};auth_time?:number};
class HttpError extends Error{status:number;publicMessage:string;constructor(status:number,publicMessage:string,internalMessage?:string){super(internalMessage||publicMessage);this.status=status;this.publicMessage=publicMessage;}}
function allowedOrigins(){const extra=(Deno.env.get("RODIOS_ALLOWED_ORIGINS")||"").split(",").map(x=>x.trim()).filter(Boolean);return new Set([DEFAULT_ORIGIN,...extra]);}
function corsHeaders(req:Request){const origin=req.headers.get("origin")||"";const h:Record<string,string>={"Access-Control-Allow-Headers":"content-type, apikey, x-firebase-id-token, x-firebase-appcheck","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Max-Age":"86400","Vary":"Origin"};if(origin&&allowedOrigins().has(origin))h["Access-Control-Allow-Origin"]=origin;return h;}
function assertOrigin(req:Request){const origin=req.headers.get("origin")||"";if(origin&&!allowedOrigins().has(origin))throw new HttpError(403,"Origin not allowed");}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});}
function getAdminClient(){const url=(Deno.env.get("SUPABASE_URL")||"").trim();let key=(Deno.env.get("SUPABASE_SECRET_KEY")||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"").trim();if(!key){try{const named=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}");key=String(named.default||Object.values(named)[0]||"").trim();}catch(_){}}if(!url||!key)throw new Error("Supabase server credentials are not configured");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
let certCache:{keys:Record<string,string>;exp:number}|null=null;
function parseMaxAge(v:string|null){const m=String(v||"").match(/(?:^|,)\s*max-age=(\d+)/i);return m?Math.max(60,Number(m[1])||300):300;}
async function getFirebaseCerts(){const now=Date.now();if(certCache&&certCache.exp>now)return certCache.keys;const res=await fetch(FIREBASE_CERTS_URL,{headers:{Accept:"application/json"}});if(!res.ok)throw new Error(`Firebase certificate endpoint returned ${res.status}`);const keys=await res.json();if(!keys||typeof keys!=="object")throw new Error("Firebase certificate response is invalid");certCache={keys:keys as Record<string,string>,exp:now+parseMaxAge(res.headers.get("cache-control"))*1000};return certCache.keys;}
async function verifyFirebaseIdToken(token:string):Promise<FirebasePayload>{if(!token||token.length>20000)throw new Error("Missing or malformed Firebase ID token");const header=decodeProtectedHeader(token);if(header.alg!=="RS256"||!header.kid)throw new Error("Invalid Firebase token header");const certs=await getFirebaseCerts(),pem=certs[String(header.kid)];if(!pem)throw new Error("Unknown Firebase signing key");const key=await importX509(pem,"RS256");const {payload}=await jwtVerify(token,key,{algorithms:["RS256"],issuer:FIREBASE_ISSUER,audience:FIREBASE_PROJECT_ID});const p=payload as FirebasePayload,now=Math.floor(Date.now()/1000);if(!p.sub||typeof p.sub!=="string"||p.sub.length>128)throw new Error("Invalid Firebase subject");if(!p.iat||p.iat>now+60)throw new Error("Invalid Firebase issued-at");if(!p.auth_time||p.auth_time>now+60)throw new Error("Invalid Firebase auth_time");if(p.firebase?.sign_in_provider!=="phone")throw new Error("Firebase phone authentication required");if(!p.phone_number)throw new Error("Verified phone number missing");return p;}
async function verifyAppCheckToken(token:string){if(!token||token.length>20000)throw new Error("Missing or malformed Firebase App Check token");const header=decodeProtectedHeader(token);if(header.alg!=="RS256"||header.typ!=="JWT"||!header.kid)throw new Error("Invalid App Check header");const {payload}=await jwtVerify(token,APP_CHECK_JWKS,{algorithms:["RS256"],issuer:APP_CHECK_ISSUER,audience:APP_CHECK_AUDIENCE});if(payload.sub!==FIREBASE_WEB_APP_ID)throw new Error("App Check app id is not authorized");}
function digits(p:string){return String(p||"").replace(/\D/g,"");}
function localPhoneKey(p:string){const d=digits(p);return d.startsWith("30")&&d.length===12?d.slice(2):d;}
function belongsPhone(issue:any,phone:string){const expected=localPhoneKey(phone);if(!expected)return false;return [issue?.citizenMobile,issue?.citizenPhone,issue?.mobile].map(localPhoneKey).filter(Boolean).includes(expected);}
function cleanText(v:unknown,max:number){return String(v??"").trim().slice(0,max);}
function cleanNullableNumber(v:unknown,min:number,max:number){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null;}
function cleanCitizenRef(v:unknown){const s=String(v||"").trim();if(/^\d{6}$/.test(s))return s;const a=new Uint32Array(1);crypto.getRandomValues(a);return String(100000+(a[0]%900000));}
function cleanAttachments(v:unknown,phoneDigits:string){if(!Array.isArray(v))return [];const prefix=`citizen/${phoneDigits}/`;return v.slice(0,20).flatMap((x:any)=>{const path=cleanText(x?.path,600).replace(/^\/+/,"");if(!path||!path.startsWith(prefix)||path.includes(".."))return [];return [{name:cleanText(x?.name,160)||"attachment",type:cleanText(x?.type,120),size:Math.max(0,Math.min(Number(x?.size)||0,50*1024*1024)),path,url:null}];});}
function athensParts(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Athens",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const get=(t:string)=>parts.find(p=>p.type===t)?.value||"";return{date:`${get("year")}-${get("month")}-${get("day")}`,time:`${get("hour")}:${get("minute")}`};}
async function consumeQuota(admin:any,scope:string,actor:string,limit:number){const {data,error}=await admin.rpc("rodios_consume_edge_quota",{p_scope:scope,p_actor_key:actor,p_limit:limit});if(error)throw new Error(`Rate-limit RPC failed: ${error.message}`);if(data!==true)throw new HttpError(429,"Πάρα πολλές αιτήσεις. Δοκιμάστε ξανά αργότερα.");}
async function listCitizenIssues(admin:any,uid:string,phone:string){const {data:uidRows,error:uidError}=await admin.from("rodios_issues").select("id, data, updated_at").is("deleted_at",null).eq("data->>source","citizen").eq("data->>citizenAuthUid",uid).order("updated_at",{ascending:false}).limit(500);if(uidError)throw uidError;const {data:legacyRows,error:legacyError}=await admin.from("rodios_issues").select("id, data, updated_at").is("deleted_at",null).eq("data->>source","citizen").order("updated_at",{ascending:false}).limit(1000);if(legacyError)throw legacyError;const byId=new Map<string,any>();for(const row of uidRows||[])byId.set(row.id,{...row.data,id:row.id});for(const row of legacyRows||[]){if(byId.has(row.id)||row?.data?.citizenAuthUid)continue;if(belongsPhone(row.data,phone))byId.set(row.id,{...row.data,id:row.id});}return [...byId.values()].sort((a,b)=>String(b.updatedAt||b.createdAt||"").localeCompare(String(a.updatedAt||a.createdAt||"")));}
async function getIssue(admin:any,id:string){const {data,error}=await admin.from("rodios_issues").select("id, data").eq("id",id).is("deleted_at",null).maybeSingle();if(error)throw error;return data?{...data.data,id:data.id}:null;}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS"){try{assertOrigin(req);return new Response(null,{status:204,headers:corsHeaders(req)});}catch(_){return json(req,{ok:false,error:"Origin not allowed"},403);}}if(req.method!=="POST")return json(req,{ok:false,error:"Method not allowed"},405);
try{assertOrigin(req);const length=Number(req.headers.get("content-length")||"0");if(length>MAX_JSON_BYTES)throw new HttpError(413,"Το αίτημα είναι πολύ μεγάλο.");let body:any;try{body=await req.json();}catch{throw new HttpError(400,"Invalid JSON");}
const idToken=req.headers.get("x-firebase-id-token")||String(body?.idToken||""),appCheckToken=req.headers.get("x-firebase-appcheck")||"";const [claims]=await Promise.all([verifyFirebaseIdToken(idToken),verifyAppCheckToken(appCheckToken)]);const phone=String(claims.phone_number||""),phoneDigits=digits(phone);if(phoneDigits.length<10||phoneDigits.length>15)throw new HttpError(401,"Invalid verified phone");const admin=getAdminClient();const action=cleanText(body?.action,20),limits:Record<string,number>={list:120,submit:20,update:60};if(!(action in limits))throw new HttpError(400,"Unknown action");await consumeQuota(admin,`citizen-bridge:${action}`,String(claims.sub),limits[action]);
if(action==="list")return json(req,{ok:true,issues:await listCitizenIssues(admin,String(claims.sub),phone)});
if(action==="submit"){const inc=body?.issue&&typeof body.issue==="object"?body.issue:{};const citizenName=cleanText(inc.citizenName,180),municipality=cleanText(inc.municipality,160),category=cleanText(inc.category,160),title=cleanText(inc.title,220),location=cleanText(inc.location,300),description=cleanText(inc.description,5000);if(!citizenName||!municipality||!category||!title||!location||!description)throw new HttpError(400,"Λείπουν υποχρεωτικά πεδία.");const nowIso=new Date().toISOString(),local=athensParts();const issue={id:`cit_${crypto.randomUUID()}`,citizenRef:cleanCitizenRef(inc.citizenRef),issueNum:"",modifiesRef:cleanText(inc.modifiesRef,60)||null,createdAt:nowIso,serverReceivedAt:nowIso,source:"citizen",date:local.date,time:local.time,receiptMethod:"Αίτημα Πολίτη",citizenAuthUid:String(claims.sub),citizenName,citizenAddr:"",citizenMobile:phone,citizenPhone:phone,citizenEmail:"",contactInfo:`📱 ${phone}`,location,municipality,category,title,description,priority:"",danger:"Όχι",inspection:"Όχι",status:"Προς ενέργεια",notes:"",municipalNum:"",mapLat:cleanNullableNumber(inc.mapLat,-90,90),mapLng:cleanNullableNumber(inc.mapLng,-180,180),attachments:cleanAttachments(inc.attachments,phoneDigits),completionDate:""};const {error}=await admin.from("rodios_issues").insert({id:issue.id,data:issue,deleted_at:null});if(error)throw error;return json(req,{ok:true,issue});}
const inc=body?.issue&&typeof body.issue==="object"?body.issue:{},id=cleanText(inc.id,180);if(!id)throw new HttpError(400,"Missing id");const orig=await getIssue(admin,id);if(!orig)throw new HttpError(404,"Not found");const uidOwned=orig.citizenAuthUid&&String(orig.citizenAuthUid)===String(claims.sub),legacyOwned=!orig.citizenAuthUid&&belongsPhone(orig,phone);if(!uidOwned&&!legacyOwned)throw new HttpError(403,"Forbidden");const createdMs=Date.parse(String(orig.createdAt||""));if(!Number.isFinite(createdMs))throw new HttpError(409,"Modify window expired");const ageMin=(Date.now()-createdMs)/60000;if(ageMin< -2||ageMin>MODIFY_WINDOW_MIN)throw new HttpError(409,"Modify window expired");const updated={...orig,citizenAuthUid:String(claims.sub),citizenName:cleanText(inc.citizenName??orig.citizenName,180),municipality:cleanText(inc.municipality??orig.municipality,160),category:cleanText(inc.category??orig.category,160),title:cleanText(inc.title??orig.title,220),location:cleanText(inc.location??orig.location,300),description:cleanText(inc.description??orig.description,5000),mapLat:cleanNullableNumber(inc.mapLat??orig.mapLat,-90,90),mapLng:cleanNullableNumber(inc.mapLng??orig.mapLng,-180,180),attachments:cleanAttachments(Array.isArray(inc.attachments)?inc.attachments:orig.attachments,phoneDigits),citizenMobile:phone,citizenPhone:phone,contactInfo:`📱 ${phone}`,lastModifiedAt:new Date().toISOString()};const {error}=await admin.from("rodios_issues").update({data:updated}).eq("id",id).is("deleted_at",null);if(error)throw error;return json(req,{ok:true,issue:updated});
}catch(err){const e=err instanceof Error?err:new Error(String(err));if(e instanceof HttpError){console.warn(`[citizen-bridge] ${e.status}: ${e.message}`);return json(req,{ok:false,error:e.publicMessage},e.status);}console.error("[citizen-bridge]",e);const authFailure=/Firebase|App Check|phone|token|subject|issued-at|auth_time/i.test(e.message);return json(req,{ok:false,error:authFailure?"Authentication failed":"Server request failed"},authFailure?401:500);}});
