import { ContentInfo, SignedData, type Certificate } from "npm:pkijs@3.4.0";
import { assertAllowedOrigin, consumeHourlyQuota, corsHeaders, handleError, HttpError, json, requireActiveStaff } from "../_shared/rodios-staff-auth.ts";
const MAX_PDF_BYTES=25*1024*1024,MAX_BASE64_CHARS=Math.ceil(MAX_PDF_BYTES/3)*4+4096,MAX_SIGNATURES=20;
type ByteRange={a:number;b:number;c:number;d:number;end1:number;end2:number};
type SignatureDetail={index:number;cryptographicValid:boolean;coversFinalRevision:boolean;signer:string;certificatePresent:boolean;reason?:string};
function decodePdfBase64(input:string){const raw=String(input||"").trim();if(!raw)throw new HttpError(400,"Λείπει το PDF.");if(raw.length>MAX_BASE64_CHARS)throw new HttpError(413,"Το PDF ξεπερνά το επιτρεπτό μέγεθος.");const b64=(raw.includes(",")?raw.slice(raw.indexOf(",")+1):raw).replace(/\s+/g,"");if(!b64||!/^[A-Za-z0-9+/]*={0,2}$/.test(b64))throw new HttpError(400,"Μη έγκυρη κωδικοποίηση PDF.");const estimated=Math.floor(b64.length*3/4)-(b64.endsWith("==")?2:b64.endsWith("=")?1:0);if(estimated<=0||estimated>MAX_PDF_BYTES)throw new HttpError(413,"Το PDF ξεπερνά το επιτρεπτό μέγεθος.");let bin:string;try{bin=atob(b64);}catch{throw new HttpError(400,"Μη έγκυρη κωδικοποίηση PDF.");}const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);if(out.length<5||String.fromCharCode(...out.slice(0,5))!=="%PDF-")throw new HttpError(400,"Το αρχείο δεν είναι έγκυρο PDF.");return out;}
function latin1(bytes:Uint8Array){return new TextDecoder("windows-1252").decode(bytes);}
function findByteRanges(bytes:Uint8Array){const text=latin1(bytes),re=/\/ByteRange\s*\[\s*(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s*\]/g,out:ByteRange[]=[],seen=new Set<string>();let m:RegExpExecArray|null;while((m=re.exec(text))!==null&&out.length<MAX_SIGNATURES){const [a,b,c,d]=[Number(m[1]),Number(m[2]),Number(m[3]),Number(m[4])];if(![a,b,c,d].every(Number.isSafeInteger)||a<0||b<0||c<0||d<0)continue;const end1=a+b,end2=c+d;if(end1<a||end2<c||end1>c||end2>bytes.length)continue;const key=`${a}:${b}:${c}:${d}`;if(seen.has(key))continue;seen.add(key);out.push({a,b,c,d,end1,end2});}return out.sort((x,y)=>x.end2-y.end2);}
function concatRanges(bytes:Uint8Array,r:ByteRange){const first=bytes.subarray(r.a,r.end1),second=bytes.subarray(r.c,r.end2),out=new Uint8Array(first.length+second.length);out.set(first,0);out.set(second,first.length);return out.buffer;}
function hexToBytes(hex:string){if(!hex||hex.length%2)throw new Error("CMS hex is malformed");const out=new Uint8Array(hex.length/2);for(let i=0;i<out.length;i++){const v=Number.parseInt(hex.slice(i*2,i*2+2),16);if(!Number.isFinite(v))throw new Error("CMS hex is malformed");out[i]=v;}return out;}
function derObjectLength(bytes:Uint8Array){if(bytes.length<2||bytes[0]!==0x30)throw new Error("CMS is not a DER SEQUENCE");const first=bytes[1];if((first&0x80)===0){const total=2+first;if(total>bytes.length)throw new Error("CMS DER length exceeds Contents");return total;}const n=first&0x7f;if(n<1||n>4||bytes.length<2+n)throw new Error("CMS DER length is invalid");let len=0;for(let i=0;i<n;i++)len=len*256+bytes[2+i];const total=2+n+len;if(total>bytes.length)throw new Error("CMS DER length exceeds Contents");return total;}
function extractCms(bytes:Uint8Array,r:ByteRange){const gap=bytes.subarray(r.end1,r.c),text=latin1(gap),lt=text.indexOf("<"),gt=lt>=0?text.indexOf(">",lt+1):-1;if(lt<0||gt<0)throw new Error("PDF signature Contents not found");const hex=text.slice(lt+1,gt).replace(/\s+/g,"");if(!/^[0-9A-Fa-f]+$/.test(hex))throw new Error("PDF signature Contents is not hexadecimal CMS");const padded=hexToBytes(hex),len=derObjectLength(padded);return padded.slice(0,len);}
function certCommonName(cert:any){try{const vals=cert?.subject?.typesAndValues||[],cn=vals.find((x:any)=>x?.type==="2.5.4.3"),v=cn?.value?.valueBlock?.value;if(typeof v==="string")return v.trim().slice(0,160);}catch(_){}return "";}
async function verifyOne(bytes:Uint8Array,r:ByteRange,index:number):Promise<SignatureDetail>{const coversFinalRevision=r.end2===bytes.length;try{const cmsBytes=extractCms(bytes,r),contentInfo=ContentInfo.fromBER(cmsBytes.buffer);if(contentInfo.contentType!==ContentInfo.SIGNED_DATA)throw new Error("Contents is not CMS SignedData");const signedData=new SignedData({schema:contentInfo.content});if(!signedData.signerInfos?.length)throw new Error("CMS has no signer");if(signedData.signerInfos.length>4)throw new Error("Unexpected signer count in one PDF signature container");const detached=concatRanges(bytes,r);let allValid=true,signer="",certificatePresent=false;for(let signerIndex=0;signerIndex<signedData.signerInfos.length;signerIndex++){const result:any=await signedData.verify({signer:signerIndex,data:detached,checkChain:false,extendedMode:true});const ok=result===true||result?.signatureVerified===true;if(!ok)allValid=false;const cert=result?.signerCertificate as Certificate|null|undefined;if(cert){certificatePresent=true;if(!signer)signer=certCommonName(cert);}}return{index,cryptographicValid:allValid,coversFinalRevision,signer,certificatePresent,...(!allValid?{reason:"CMS signature verification failed"}:{})};}catch(e){return{index,cryptographicValid:false,coversFinalRevision,signer:"",certificatePresent:false,reason:e instanceof Error?e.message.slice(0,240):"Signature verification failed"};}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS"){try{assertAllowedOrigin(req);return new Response(null,{status:204,headers:corsHeaders(req)});}catch(e){return handleError(req,"verify-pdf-signatures",e);}}if(req.method!=="POST")return json(req,{valid:false,verified:false,error:"Method not allowed"},405);try{const ctx=await requireActiveStaff(req);await consumeHourlyQuota(ctx.admin,"verify-pdf-signatures",ctx.user.id,60);let body:any;try{body=await req.json();}catch{throw new HttpError(400,"Invalid JSON");}const bytes=decodePdfBase64(body?.pdfBase64||""),ranges=findByteRanges(bytes);if(!ranges.length)return json(req,{valid:false,verified:false,source:"edge-cms-crypto",count:0,detectedCount:0,signers:[],integrityOk:false,certificatesOk:false,trustedChainConfigured:false,trustMode:"cryptographic-integrity-only",message:"Δεν βρέθηκε επαληθεύσιμη ψηφιακή υπογραφή PDF.",details:[]});const details:SignatureDetail[]=[];for(let i=0;i<ranges.length;i++)details.push(await verifyOne(bytes,ranges[i],i+1));const cryptoValidCount=details.filter(x=>x.cryptographicValid).length,last=details[details.length-1],allCryptoValid=cryptoValidCount===details.length,finalRevisionCovered=!!last?.coversFinalRevision,verified=allCryptoValid&&finalRevisionCovered,signers=[...new Set(details.map(x=>x.signer).filter(Boolean))],certificatesOk=details.every(x=>x.certificatePresent);return json(req,{valid:verified,verified,source:"edge-cms-crypto",count:cryptoValidCount,detectedCount:details.length,signers,integrityOk:verified,certificatesOk,trustedChainConfigured:false,trustMode:"cryptographic-integrity-only",message:verified?`Επαληθεύτηκαν κρυπτογραφικά ${cryptoValidCount} ψηφιακές υπογραφές.`:"Η κρυπτογραφική επαλήθευση του PDF απέτυχε ή το τελικό αρχείο περιέχει μη υπογεγραμμένες μεταγενέστερες αλλαγές.",details});}catch(e){return handleError(req,"verify-pdf-signatures",e);}});
