-- RODIOS release hardening: soft-delete boundary, metadata audit trail, server timestamps.
begin;

-- ---------------------------------------------------------------------------
-- 1. Server-controlled updated_at timestamps.
-- ---------------------------------------------------------------------------
create or replace function public.rodios_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end $$;

revoke all on function public.rodios_touch_updated_at() from public, anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array[
    'rodios_app_users','rodios_issues','rodios_work_orders',
    'rodios_payments','rodios_settings','rodios_service_staff'
  ] loop
    execute format('drop trigger if exists trg_%I_touch_updated_at on public.%I', t, t);
    execute format('create trigger trg_%I_touch_updated_at before update on public.%I for each row execute function public.rodios_touch_updated_at()', t, t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 2. Minimal audit metadata. No business payload / citizen PII is copied here.
-- ---------------------------------------------------------------------------
create table if not exists public.rodios_audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_uid uuid null,
  actor_role text null,
  table_name text not null,
  row_id text null,
  action text not null,
  source text null
);
create index if not exists idx_rodios_audit_log_occurred_at
  on public.rodios_audit_log(occurred_at desc);
create index if not exists idx_rodios_audit_log_row
  on public.rodios_audit_log(table_name,row_id,occurred_at desc);
alter table public.rodios_audit_log enable row level security;
revoke all on table public.rodios_audit_log from public, anon, authenticated;

create or replace function public.rodios_audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row jsonb;
  v_old jsonb;
  v_action text := lower(tg_op);
  v_id text;
  v_source text;
begin
  v_row := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  v_old := case when tg_op = 'UPDATE' then to_jsonb(old) else null end;

  if tg_op = 'UPDATE'
     and (v_old->>'deleted_at') is null
     and (v_row->>'deleted_at') is not null then
    v_action := 'soft_delete';
  end if;

  v_id := coalesce(v_row->>'id', v_row->>'key', '');
  v_source := nullif(coalesce(v_row->'data'->>'source',''), '');

  insert into public.rodios_audit_log(actor_uid,actor_role,table_name,row_id,action,source)
  values (auth.uid(), auth.role(), tg_table_name, nullif(v_id,''), v_action, v_source);

  return case when tg_op = 'DELETE' then old else new end;
end $$;
revoke all on function public.rodios_audit_row_change() from public, anon, authenticated;

do $$
declare t text;
begin
  foreach t in array array[
    'rodios_app_users','rodios_issues','rodios_work_orders',
    'rodios_payments','rodios_settings','rodios_service_staff'
  ] loop
    execute format('drop trigger if exists trg_%I_audit on public.%I', t, t);
    execute format('create trigger trg_%I_audit after insert or update or delete on public.%I for each row execute function public.rodios_audit_row_change()', t, t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 3. Physical deletes are no longer a browser capability.
--    Operational users may update business columns, but never deleted_at.
-- ---------------------------------------------------------------------------
revoke delete on table
  public.rodios_issues,
  public.rodios_work_orders,
  public.rodios_payments,
  public.rodios_service_staff
from authenticated;

revoke update on table
  public.rodios_issues,
  public.rodios_work_orders,
  public.rodios_payments,
  public.rodios_service_staff
from authenticated;

grant update(data) on table public.rodios_issues to authenticated;
grant update(issue_id,data) on table public.rodios_work_orders to authenticated;
grant update(work_order_id,data) on table public.rodios_payments to authenticated;
grant update(data) on table public.rodios_service_staff to authenticated;

-- Remove direct DELETE policies as defense in depth. Admin deletion goes through RPC.
drop policy if exists issues_delete_admin_v2 on public.rodios_issues;
drop policy if exists workorders_delete_admin_v2 on public.rodios_work_orders;
drop policy if exists payments_delete_admin_v2 on public.rodios_payments;
drop policy if exists svcstaff_delete_admin_v2 on public.rodios_service_staff;

-- App-user lifecycle already goes through manage-app-user and remains admin-only.
-- Keep its existing RLS because the Edge Function performs Auth + profile lifecycle together.

create or replace function public.rodios_soft_delete(p_entity text, p_ids text[])
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer := 0;
  v_role text;
begin
  if p_ids is null or cardinality(p_ids) < 1 or cardinality(p_ids) > 500 then
    raise exception 'invalid soft-delete id set' using errcode='22023';
  end if;
  if exists (select 1 from unnest(p_ids) x where x is null or length(trim(x)) < 1 or length(x) > 220) then
    raise exception 'invalid soft-delete id' using errcode='22023';
  end if;

  v_role := auth.role();
  if coalesce(v_role,'') <> 'service_role' and not public.rodios_is_admin() then
    raise exception 'Administrator permission required' using errcode='42501';
  end if;

  case p_entity
    when 'rodios_issues' then
      update public.rodios_issues set deleted_at=now() where id=any(p_ids) and deleted_at is null;
    when 'rodios_work_orders' then
      update public.rodios_work_orders set deleted_at=now() where id=any(p_ids) and deleted_at is null;
    when 'rodios_payments' then
      update public.rodios_payments set deleted_at=now() where id=any(p_ids) and deleted_at is null;
    when 'rodios_service_staff' then
      update public.rodios_service_staff set deleted_at=now() where id=any(p_ids) and deleted_at is null;
    else
      raise exception 'unsupported soft-delete entity' using errcode='22023';
  end case;

  get diagnostics v_count = row_count;
  return v_count;
end $$;
revoke all on function public.rodios_soft_delete(text,text[]) from public, anon;
grant execute on function public.rodios_soft_delete(text,text[]) to authenticated, service_role;

commit;

-- Read-only post migration checks.
select table_name, privilege_type
from information_schema.role_table_grants
where grantee='authenticated'
  and table_schema='public'
  and table_name in ('rodios_issues','rodios_work_orders','rodios_payments','rodios_service_staff')
order by table_name, privilege_type;
